# -*- mode: ruby -*-
# vi: set ft=ruby :

# Re-adapted from: https://atlas.hashicorp.com/AndrewDryga/boxes/vagrant-box-osx/

Vagrant.configure(2) do |config|
  config.vm.box = "http://files.dryga.com/boxes/osx-yosemite-0.2.1.box"
  config.vm.hostname = "osx"

  config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.50.5"

  # https://github.com/AndrewDryga/vagrant-box-osx/issues/24
  config.vm.synced_folder "/home/giampaolo/svn/", "/vagrant",
    id: "vagrant-root",
    :nfs => true,
    :mount_options => ['nolock,vers=3,udp,noatime,actimeo=1,resvport'],
    :export_options => ['async,insecure,no_subtree_check,no_acl,no_root_squash']

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4092"
  end
end
