Vagrant.configure(2) do |config|
  config.vm.box = "jhcook/osx-elcapitan-10.11"
  config.vm.hostname = "osx-elcaptain"

  config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.50.58"

  # https://github.com/AndrewDryga/vagrant-box-osx/issues/24
  config.vm.synced_folder "/home/giampaolo/svn/", "/vagrant",
    id: "vagrant-root",
    :nfs => true,
    :mount_options => ['nolock,vers=3,udp,noatime,actimeo=1,resvport'],
    :export_options => ['async,insecure,no_subtree_check,no_acl,no_root_squash']

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4092"
  end
end
