Vagrant.configure(2) do |config|
  config.vm.box = "ryanmaclean/openbsd-5.9"
  config.vm.hostname = "openbsd"
  config.ssh.shell = "sh"
  config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.50.78"
  config.vm.synced_folder "/home/giampaolo/svn/", "/vagrant", :nfs => { :mount_options =>  ["dmode=777","fmode=777"] }

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
