Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-12.0-CURRENT"
  config.vm.hostname = "freebsd12"
  config.ssh.shell = "bash"
  config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.50.29"
  config.vm.synced_folder "/home/giampaolo/svn", "/vagrant", :nfs => { :mount_options =>  ["dmode=777","fmode=777"] }
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.memory = "2048"
    vb.cpus = "2"
  end
end
