#!/bin/bash

# load utility functions
source /home/giampaolo/.bashrc

set -x
set -e


if [[ $PLATFORM    == *"linux"* ]]; then
    _set_sudo_no_passwd

    # disable error reports
    append-to-file /etc/default/apport "enabled=0"

    # remove unwanted apps
    sudo apt-get remove -y totem gedit
fi

