#!/usr/bin/env bash

set -e

# load utility functions
source ~/.bashrc

set -x

if [ "$(id -u)" != "0" ]; then
    echo "must be root"
    exit 1
fi

# Ubuntu / Debian
do_apt() {
    # add chrome ppa http://www.ubuntuupdates.org/ppa/google_chrome
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    rm /etc/apt/sources.list.d/google.list
    sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

    # add skype ppa http://www.ubuntugeek.com/how-to-install-skype-in-ubuntu-12-04precise.html
    apt-add-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

    add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"

    # install all essential packages
    base="msttcorefonts vim build-essential ubuntu-restricted-extras rar unrar sudo"
    net="curl wget"
    dev="mercurial git colordiff libreadline-dev libncurses*-dev python-dev python3-dev build-essential ack-grep libffi-dev libssl-dev"
    media="vlc ffmpeg"
    sys="openssh-server screen htop virtualbox xawtv indicator-cpufreq"
    ppa="google-chrome-stable skype"
    apt-get update
    apt-get install -y $base $net $dev $media $sys $ppa
    apt-get install -y linux-headers-`uname -r`
    install_pip
    python -m pip install --upgrade thefuck
}

# FreeBSD (tipically)
do_pkg() {
    # install (requires root)
    if ! type -P > /dev/null; then
        cd /usr/ports/security/sudo/ && make install clean
    fi

    # install base packages
    pkg install -y git vim screen gcc wget curl

    # install pip
    sh-py-install-pip python
    python -m pip install --upgrade thefuck
}


if type -P apt > /dev/null; then
    do_apt
elif type -P pkg > /dev/null; then
    do_pkg
fi
