#!/usr/bin/env sh

set -e
set -x

# PIP_URL="https://bootstrap.pypa.io/get-pip.py"
SUDO=""


command_exists() {
    if command -v $1 > /dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}


check_privileges() {
    if [ "$(id -u)" != "0" ]; then
        if command_exists 'sudo' ; then
            SUDO="sudo"
        else
            echo "must be root"
            exit 1
        fi
    fi
}


# ...in case wget/curl are missing
# usage: sh_net_httpfetch <url> [<file>]
# sh_net_httpfetch() {
#     url=$1 dest=$2 python << END
# from __future__ import print_function
# if 1:
#     import os, urllib2, sys
#     url = os.environ['url']
#     dest = os.environ['dest']
#     if not url:
#         sys.exit('usage: sh_net_httpfetch <url> [<file>]')
#     print("getting %s to %s" % (url, dest), file=sys.stderr)
#     if not '://' in url:
#         url = 'http://' + url
#     # try to disable cache
#     req = urllib2.Request(url)
#     req.add_header('Cache-Control', 'max-age=0')
#     req.add_header('Pragma', 'no-cache')
#     url = urllib2.urlopen(req)
#     data = url.read()
#     if dest:
#         f = open(dest, 'w')
#     else:
#         f = sys.stdout
#     with f:
#         f.write(data)
# END
# }


# install_pip() {
#     if type -P pip > /dev/null; then
#         sh_net_httpfetch $PIP_URL > /tmp/get-pip.py
#         python /tmp/get-pip.py
#         rm /tmp/get-pip.py
#     fi
# }


# Ubuntu / Debian
do_apt() {
    # add chrome ppa http://www.ubuntuupdates.org/ppa/google_chrome
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | $SUDO apt-key add -
    $SUDO rm -f /etc/apt/sources.list.d/google.list
    $SUDO sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

    # add skype ppa http://www.ubuntugeek.com/how-to-install-skype-in-ubuntu-12-04precise.html
    $SUDO apt-add-repository "deb http://archive.canonical.com/ $(lsb_release -sc) partner"

    $SUDO add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner"

    # install all essential packages
    base="msttcorefonts vim build-essential ubuntu-restricted-extras sudo xclip"
    net="curl wget"
    files="tree rar unrar nfs-kernel-server"
    dev="git mercurial colordiff libreadline-dev libncurses*-dev python-dev python3-dev build-essential ack-grep libffi-dev libssl-dev libreadline-dev python-pip python3-pip"
    media="vlc ffmpeg"
    sys="openssh-server screen htop virtualbox xawtv indicator-cpufreq"
    ppa="google-chrome-stable skype"
    $SUDO apt-get update
    $SUDO apt-get install -y $base $net $files $dev $media $sys $ppa
    $SUDO apt-get install -y linux-headers-`uname -r`
    $SUDO apt-get autoremove -y
}


# FreeBSD os Solaris
do_pkg() {
    # FreeBSD
    if echo "$OSTYPE" | grep 'freebsd'; then
        $SUDO pkg install -y git vim screen gcc wget curl sudo python python3 wget curl tree xclip
    fi

    # Solaris
    if echo "$OSTYPE" | grep 'solaris'; then
        # distutils assume cc; if not installed use gcc by creating a symlink
        if ! type -P cc > /dev/null; then
            $SUDO ln -s /usr//bin/gcc /usr/local/bin/cc
        fi

        # install pkgs
        if ! type -P gcc > /dev/null; then
            $SUDO pkg install gcc
        fi
        if ! type -P vim > /dev/null; then
            $SUDO pkg install vim
        fi
    fi
}


# OSX
do_brew() {
    # install brew
    if ! type -P brew > /dev/null; then
        $SUDO ruby -e "$(curl -fsSkL raw.github.com/mistydemeo/tigerbrew/go/install)"
        $SUDO chown root /usr/local/bin/brew
    fi
    FORCE_UNSAFE_CONFIGURE=1 sudo brew install gcc git vim coreutils
}


main() {
    check_privileges

    # install pkgs
    if command_exists 'apt-get' ; then
        do_apt
    elif command_exists 'pkg' ; then
        do_pkg
    elif command_exists 'brew' ; then
        do_brew
    fi

    # install python stuff
    $SUDO python -m pip install --upgrade thefuck pip setuptools
}

main
