#!/usr/bin/env python

import os

from sysconf import DIR_HOME
from sysconf import DIR_STATIC_HOME
from sysconf import LINUX
from sysconf import safe_remove
from sysconf import safe_makedirs
from sysconf import safe_rmtree
from sysconf import sh
from sysconf import symlink
from sysconf import which


def main():
    # Copy user "hidden" config files.
    for name in os.listdir(DIR_STATIC_HOME):
        src = os.path.join(DIR_STATIC_HOME, name)
        dst = os.path.join(DIR_HOME, name)
        if name.startswith('.') and os.path.isfile(src):
            safe_remove(dst)
            symlink(src, dst)

    # configure git
    if which('git'):
        sh("git config --global push.default simple")

    if LINUX:
        srcdir = os.path.join(
            DIR_STATIC_HOME, '.config/sublime-text-3/Packages/User')
        dstdir = os.path.join(
            DIR_HOME, '.config/sublime-text-3/Packages/User')
        # safe_rmtree(dstdir)
        # safe_makedirs(os.path.dirname(dstdir))
        sh("rm -rf %s" % os.path.dirname(dstdir))
        safe_makedirs(os.path.dirname(dstdir))
        os.listdir(srcdir)
        symlink(srcdir, dstdir)


main()
