Vagrant.configure(2) do |config|
  config.vm.box = "freebsd/FreeBSD-11.0-RELEASE-p1"
  config.vm.hostname = "freebsd"
  config.ssh.shell = "sh"
  config.vm.box_download_insecure = true
  config.vm.network "private_network", ip: "192.168.50.24"
  config.vm.synced_folder "/home/giampaolo/svn/", "/vagrant", :nfs => { :mount_options =>  ["dmode=777","fmode=777"] }
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
